apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: check-run-as-nonroot-containers
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  variables:
    - name: podNonRootTrue
      expression: >
        has(object.spec.securityContext) &&
        has(object.spec.securityContext.runAsNonRoot) &&
        object.spec.securityContext.runAsNonRoot == true
  validations:
    - expression: >
        object.spec.containers.all(c,
          variables.podNonRootTrue
          ? (!has(c.securityContext) || !has(c.securityContext.runAsNonRoot) || c.securityContext.runAsNonRoot == true)
          : (has(c.securityContext) && has(c.securityContext.runAsNonRoot) && c.securityContext.runAsNonRoot == true)
        )
      message: >
        spec.containers[*].securityContext.runAsNonRoot must be set to true, unless the Pod-level spec.securityContext.runAsNonRoot is true—in which case it may be undefined or true.
