apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: check-apparmor-profile-pod
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  variables:
    - name: allowedAppArmorTypes
      expression: >
        ["RuntimeDefault","Localhost"]
  validations:
    - expression: >
        !has(object.spec.securityContext) ||
        !has(object.spec.securityContext.appArmorProfile) ||
        !has(object.spec.securityContext.appArmorProfile.type) ||
        variables.allowedAppArmorTypes.exists(t, t == object.spec.securityContext.appArmorProfile.type)
      message: >
        spec.securityContext.appArmorProfile.type must be undefined, RuntimeDefault, or Localhost.
