apiVersion: v1
kind: Namespace
metadata:
  name: prod-ml
  labels:
    validating-admission-policies.kolteq.com/enforce: restricted
    hostnetwork.validating-admission-policies.kolteq.com/enforce: "true"
    privileged-containers.validating-admission-policies.kolteq.com/enforce: "true"
    allowed-sysctls.validating-admission-policies.kolteq.com/warn: "true"
