apiVersion: v1
kind: Namespace
metadata:
  name: prod-ml
  labels:
    pss.kolteq.com/enforce: restricted
    hostnetwork.pss.kolteq.com/enforce: "true"
    privileged-containers.pss.kolteq.com/enforce: "true"
    allowed-sysctls.pss.kolteq.com/warn: "true"
