apiVersion: v1
kind: Namespace
metadata:
  name: payments
  labels:
    validating-admission-policies.kolteq.com/enforce: restricted
    validating-admission-policies.kolteq.com/privileged-containers: "false"
    validating-admission-policies.kolteq.com/allowed-hostports-containers: "false"
