apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    pss.kolteq.com/audit: restricted
    run-as-user-pod.pss.kolteq.com/audit: "false"
    seccomp-profile-pod.pss.kolteq.com/warn: "true"
