apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    validating-admission-policies.kolteq.com/audit: restricted
    validating-admission-policies.kolteq.com/run-as-user-pod: "false"
    seccomp-profile-pod.validating-admission-policies.kolteq.com/warn: "true"
