apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: check-startupprobe-tcpsocket-host-initcontainers
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  validations:
    - expression: >
        !has(object.spec.initContainers) ||
        object.spec.initContainers.all(ic,
          !has(ic.startupProbe) ||
          !has(ic.startupProbe.tcpSocket) ||
          !has(ic.startupProbe.tcpSocket.host) ||
          ic.startupProbe.tcpSocket.host == ""
        )
      message: >
        spec.initContainers[*].startupProbe.tcpSocket.host must be undefined or empty ("").
