apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: check-allowed-hostports-initcontainers
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  variables:
    - name: allowedHostPorts
      # expression: >
      #   [22, 80, 443]
      expression: >
        []
  validations:
    - expression: >
        !has(object.spec.initContainers) ||
        object.spec.initContainers.all(ic,
          !has(ic.ports) ||
          ic.ports.all(p,
            !has(p.hostPort) ||
            p.hostPort == 0 ||
            variables.allowedHostPorts.exists(h, h == p.hostPort)
          )
        )
      message: >
        initContainer hostPort must be undefined, 0, or in the variables.allowedHostPorts list.
