apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: check-prestop-httpget-host-initcontainers
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  validations:
    - expression: >
        !has(object.spec.initContainers) ||
        object.spec.initContainers.all(ic,
          !has(ic.lifecycle) ||
          !has(ic.lifecycle.preStop) ||
          !has(ic.lifecycle.preStop.httpGet) ||
          !has(ic.lifecycle.preStop.httpGet.host) ||
          ic.lifecycle.preStop.httpGet.host == ""
        )
      message: >
        spec.initContainers[*].lifecycle.preStop.httpGet.host must be undefined or empty ("").
