apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: check-seccomp-profile-pod
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  variables:
    - name: allowedSeccompTypes
      expression: >
        ["RuntimeDefault","Localhost"]
  validations:
    - expression: >
        (has(object.spec.os) &&
         has(object.spec.os.name) &&
         object.spec.os.name.lowerAscii() == "windows") ||
        !has(object.spec.securityContext) ||
        !has(object.spec.securityContext.seccompProfile) ||
        !has(object.spec.securityContext.seccompProfile.type) ||
        variables.allowedSeccompTypes.exists(t, t == object.spec.securityContext.seccompProfile.type)
      message: >
        spec.securityContext.seccompProfile.type must be undefined, RuntimeDefault, or Localhost.
