apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: check-run-as-nonroot-pod
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  validations:
    - expression: >
        has(object.spec.securityContext) &&
        has(object.spec.securityContext.runAsNonRoot) &&
        object.spec.securityContext.runAsNonRoot == true
      message: >
        spec.securityContext.runAsNonRoot must be set to true. Container-level fields may be undefined/nil when this is true.
