apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: check-apparmor-profile-containers
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  variables:
    - name: allowedAppArmorTypes
      expression: >
        ["RuntimeDefault","Localhost"]
  validations:
    - expression: >
        object.spec.containers.all(c,
          !has(c.securityContext) ||
          !has(c.securityContext.appArmorProfile) ||
          !has(c.securityContext.appArmorProfile.type) ||
          variables.allowedAppArmorTypes.exists(t, t == c.securityContext.appArmorProfile.type)
        )
      message: >
        spec.containers[*].securityContext.appArmorProfile.type must be undefined, RuntimeDefault, or Localhost.
