apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: check-apparmor-profile-initcontainers
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  variables:
    - name: allowedAppArmorTypes
      expression: >
        ["RuntimeDefault","Localhost"]
  validations:
    - expression: >
        !has(object.spec.initContainers) ||
        object.spec.initContainers.all(ic,
          !has(ic.securityContext) ||
          !has(ic.securityContext.appArmorProfile) ||
          !has(ic.securityContext.appArmorProfile.type) ||
          variables.allowedAppArmorTypes.exists(t, t == ic.securityContext.appArmorProfile.type)
        )
      message: >
        spec.initContainers[*].securityContext.appArmorProfile.type must be undefined, RuntimeDefault, or Localhost.
