apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: check-allowed-volume-types
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  validations:
    - expression: >
        !has(object.spec.volumes) ||
        object.spec.volumes.all(v,
          has(v.configMap) ||
          has(v.csi) ||
          has(v.downwardAPI) ||
          has(v.emptyDir) ||
          has(v.ephemeral) ||
          has(v.persistentVolumeClaim) ||
          has(v.projected) ||
          has(v.secret)
        )
      message: >
        Each item in spec.volumes[*] must set one of: configMap, csi, downwardAPI, emptyDir,
        ephemeral, persistentVolumeClaim, projected, or secret.
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: check-allowed-volume-types-namespace-optout-warn
spec:
  policyName: check-allowed-volume-types
  validationActions:
    - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: validating-admission-policies.kolteq.com/warn
          operator: In
          values: ["restricted"]
        - key: validating-admission-policies.kolteq.com/allowed-volume-types
          operator: NotIn
          values: ["false"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: check-allowed-volume-types-namespace-optin-warn
spec:
  policyName: check-allowed-volume-types
  validationActions:
    - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: allowed-volume-types.validating-admission-policies.kolteq.com/warn
          operator: In
          values: ["true"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: check-allowed-volume-types-namespace-optout-audit
spec:
  policyName: check-allowed-volume-types
  validationActions:
    - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: validating-admission-policies.kolteq.com/audit
          operator: In
          values: ["restricted"]
        - key: validating-admission-policies.kolteq.com/allowed-volume-types
          operator: NotIn
          values: ["false"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: check-allowed-volume-types-namespace-optin-audit
spec:
  policyName: check-allowed-volume-types
  validationActions:
    - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: allowed-volume-types.validating-admission-policies.kolteq.com/audit
          operator: In
          values: ["true"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: check-allowed-volume-types-namespace-optout-deny
spec:
  policyName: check-allowed-volume-types
  validationActions:
    - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: validating-admission-policies.kolteq.com/enforce
          operator: In
          values: ["restricted"]
        - key: validating-admission-policies.kolteq.com/allowed-volume-types
          operator: NotIn
          values: ["false"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: check-allowed-volume-types-namespace-optin-deny
spec:
  policyName: check-allowed-volume-types
  validationActions:
    - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: allowed-volume-types.validating-admission-policies.kolteq.com/enforce
          operator: In
          values: ["true"]
