apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: check-apparmor-annotation-values
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  validations:
    - expression: >
        !has(object.metadata.annotations) ||
        !object.metadata.annotations.exists(k,
          k.startsWith("container.apparmor.security.beta.kubernetes.io/") &&
          !(object.metadata.annotations[k] == "runtime/default" ||
            object.metadata.annotations[k].startsWith("localhost/"))
        )
      message: >
        Annotations under container.apparmor.security.beta.kubernetes.io/* must be
        "runtime/default" or start with "localhost/". Other values are not allowed.
