apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: check-capabilities-add-netbindservice-initcontainers
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  variables:
    - name: allowedCaps
      expression: >
        ["NET_BIND_SERVICE"]
  validations:
    - expression: >
        (has(object.spec.os) &&
         has(object.spec.os.name) &&
         object.spec.os.name.lowerAscii() == "windows") ||
        !has(object.spec.initContainers) ||
        object.spec.initContainers.all(ic,
          !has(ic.securityContext) ||
          !has(ic.securityContext.capabilities) ||
          !has(ic.securityContext.capabilities.add) ||
          ic.securityContext.capabilities.add.all(cap,
            variables.allowedCaps.exists(a, a == cap)
          )
        )
      message: >
        spec.initContainers[*].securityContext.capabilities.add must be undefined/nil
        or contain only "NET_BIND_SERVICE".
