apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: check-capabilities-add-netbindservice-initcontainers
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  variables:
    - name: allowedCaps
      expression: >
        ["NET_BIND_SERVICE"]
  validations:
    - expression: >
        (has(object.spec.os) &&
         has(object.spec.os.name) &&
         object.spec.os.name.lowerAscii() == "windows") ||
        !has(object.spec.initContainers) ||
        object.spec.initContainers.all(ic,
          !has(ic.securityContext) ||
          !has(ic.securityContext.capabilities) ||
          !has(ic.securityContext.capabilities.add) ||
          ic.securityContext.capabilities.add.all(cap,
            variables.allowedCaps.exists(a, a == cap)
          )
        )
      message: >
        spec.initContainers[*].securityContext.capabilities.add must be undefined/nil
        or contain only "NET_BIND_SERVICE".
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: check-capabilities-add-netbindservice-initcontainers-namespace-optout-warn
spec:
  policyName: check-capabilities-add-netbindservice-initcontainers
  validationActions:
    - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: validating-admission-policies.kolteq.com/warn
          operator: In
          values: ["restricted"]
        - key: validating-admission-policies.kolteq.com/capabilities-add-netbindservice-initcontainers
          operator: NotIn
          values: ["false"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: check-capabilities-add-netbindservice-initcontainers-namespace-optin-warn
spec:
  policyName: check-capabilities-add-netbindservice-initcontainers
  validationActions:
    - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: capabilities-add-netbindservice-initcontainers.validating-admission-policies.kolteq.com/warn
          operator: In
          values: ["true"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: check-capabilities-add-netbindservice-initcontainers-namespace-optout-audit
spec:
  policyName: check-capabilities-add-netbindservice-initcontainers
  validationActions:
    - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: validating-admission-policies.kolteq.com/audit
          operator: In
          values: ["restricted"]
        - key: validating-admission-policies.kolteq.com/capabilities-add-netbindservice-initcontainers
          operator: NotIn
          values: ["false"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: check-capabilities-add-netbindservice-initcontainers-namespace-optin-audit
spec:
  policyName: check-capabilities-add-netbindservice-initcontainers
  validationActions:
    - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: capabilities-add-netbindservice-initcontainers.validating-admission-policies.kolteq.com/audit
          operator: In
          values: ["true"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: check-capabilities-add-netbindservice-initcontainers-namespace-optout-deny
spec:
  policyName: check-capabilities-add-netbindservice-initcontainers
  validationActions:
    - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: validating-admission-policies.kolteq.com/enforce
          operator: In
          values: ["restricted"]
        - key: validating-admission-policies.kolteq.com/capabilities-add-netbindservice-initcontainers
          operator: NotIn
          values: ["false"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: check-capabilities-add-netbindservice-initcontainers-namespace-optin-deny
spec:
  policyName: check-capabilities-add-netbindservice-initcontainers
  validationActions:
    - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: capabilities-add-netbindservice-initcontainers.validating-admission-policies.kolteq.com/enforce
          operator: In
          values: ["true"]
