apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apparmor-annotation-values/binding.yaml
  - apparmor-annotation-values/policy.yaml
  - apparmor-profile/binding.yaml
  - apparmor-profile/containers/binding.yaml
  - apparmor-profile/containers/policy.yaml
  - apparmor-profile/ephemeralcontainers/binding.yaml
  - apparmor-profile/ephemeralcontainers/policy.yaml
  - apparmor-profile/initcontainers/binding.yaml
  - apparmor-profile/initcontainers/policy.yaml
  - apparmor-profile/policy.yaml
  - capabilities-add-netbindservice/containers/binding.yaml
  - capabilities-add-netbindservice/containers/policy.yaml
  - capabilities-add-netbindservice/ephemeralcontainers/binding.yaml
  - capabilities-add-netbindservice/ephemeralcontainers/policy.yaml
  - capabilities-add-netbindservice/initcontainers/binding.yaml
  - capabilities-add-netbindservice/initcontainers/policy.yaml
  - capabilities-add/containers/binding.yaml
  - capabilities-add/containers/policy.yaml
  - capabilities-add/ephemeralcontainers/binding.yaml
  - capabilities-add/ephemeralcontainers/policy.yaml
  - capabilities-add/initcontainers/binding.yaml
  - capabilities-add/initcontainers/policy.yaml
  - capabilities-drop-all/containers/binding.yaml
  - capabilities-drop-all/containers/policy.yaml
  - capabilities-drop-all/ephemeralcontainers/binding.yaml
  - capabilities-drop-all/ephemeralcontainers/policy.yaml
  - capabilities-drop-all/initcontainers/binding.yaml
  - capabilities-drop-all/initcontainers/policy.yaml
  - hostipc/binding.yaml
  - hostipc/policy.yaml
  - hostnetwork/binding.yaml
  - hostnetwork/policy.yaml
  - hostpath-volumes/binding.yaml
  - hostpath-volumes/policy.yaml
  - hostpid/binding.yaml
  - hostpid/policy.yaml
  - hostports/containers/binding.yaml
  - hostports/containers/policy.yaml
  - hostports/ephemeralcontainers/binding.yaml
  - hostports/ephemeralcontainers/policy.yaml
  - hostports/initcontainers/binding.yaml
  - hostports/initcontainers/policy.yaml
  - livenessprobe-httpget-host/container/binding.yaml
  - livenessprobe-httpget-host/container/policy.yaml
  - livenessprobe-httpget-host/initcontainers/binding.yaml
  - livenessprobe-httpget-host/initcontainers/policy.yaml
  - livenessprobe-tcpsocket-host/containers/binding.yaml
  - livenessprobe-tcpsocket-host/containers/policy.yaml
  - livenessprobe-tcpsocket-host/initcontainers/binding.yaml
  - livenessprobe-tcpsocket-host/initcontainers/policy.yaml
  - poststart-httpget-host/containers/binding.yaml
  - poststart-httpget-host/containers/policy.yaml
  - poststart-httpget-host/initcontainers/binding.yaml
  - poststart-httpget-host/initcontainers/policy.yaml
  - poststart-tcpsocket-host/containers/binding.yaml
  - poststart-tcpsocket-host/containers/policy.yaml
  - poststart-tcpsocket-host/initcontainers/binding.yaml
  - poststart-tcpsocket-host/initcontainers/policy.yaml
  - prestop-httpget-host/containers/binding.yaml
  - prestop-httpget-host/containers/policy.yaml
  - prestop-httpget-host/initcontainers/binding.yaml
  - prestop-httpget-host/initcontainers/policy.yaml
  - prestop-tcpsocket-host/containers/binding.yaml
  - prestop-tcpsocket-host/containers/policy.yaml
  - prestop-tcpsocket-host/initcontainers/binding.yaml
  - prestop-tcpsocket-host/initcontainers/policy.yaml
  - privilege-escalation/containers/binding.yaml
  - privilege-escalation/containers/policy.yaml
  - privilege-escalation/ephemeralcontainers/binding.yaml
  - privilege-escalation/ephemeralcontainers/policy.yaml
  - privilege-escalation/initcontainers/binding.yaml
  - privilege-escalation/initcontainers/policy.yaml
  - privileged/containers/binding.yaml
  - privileged/containers/policy.yaml
  - privileged/ephemeralcontainers/binding.yaml
  - privileged/ephemeralcontainers/policy.yaml
  - privileged/initcontainers/binding.yaml
  - privileged/initcontainers/policy.yaml
  - procmount/containers/binding.yaml
  - procmount/containers/policy.yaml
  - procmount/ephemeralcontainers/binding.yaml
  - procmount/ephemeralcontainers/policy.yaml
  - procmount/initcontainers/binding.yaml
  - procmount/initcontainers/policy.yaml
  - readinessprobe-httpget-host/containers/binding.yaml
  - readinessprobe-httpget-host/containers/policy.yaml
  - readinessprobe-httpget-host/initcontainers/binding.yaml
  - readinessprobe-httpget-host/initcontainers/policy.yaml
  - readinessprobe-tcpsocket-host/containers/binding.yaml
  - readinessprobe-tcpsocket-host/containers/policy.yaml
  - readinessprobe-tcpsocket-host/initcontainers/binding.yaml
  - readinessprobe-tcpsocket-host/initcontainers/policy.yaml
  - run-as-nonroot/binding.yaml
  - run-as-nonroot/containers/binding.yaml
  - run-as-nonroot/containers/policy.yaml
  - run-as-nonroot/ephemeralcontainers/binding.yaml
  - run-as-nonroot/ephemeralcontainers/policy.yaml
  - run-as-nonroot/initcontainers/binding.yaml
  - run-as-nonroot/initcontainers/policy.yaml
  - run-as-nonroot/policy.yaml
  - run-as-user/binding.yaml
  - run-as-user/containers/binding.yaml
  - run-as-user/containers/policy.yaml
  - run-as-user/ephemeralcontainers/binding.yaml
  - run-as-user/ephemeralcontainers/policy.yaml
  - run-as-user/initcontainers/binding.yaml
  - run-as-user/initcontainers/policy.yaml
  - run-as-user/policy.yaml
  - seccomp-profile-restricted/binding.yaml
  - seccomp-profile-restricted/containers/binding.yaml
  - seccomp-profile-restricted/containers/policy.yaml
  - seccomp-profile-restricted/ephemeralcontainers/binding.yaml
  - seccomp-profile-restricted/ephemeralcontainers/policy.yaml
  - seccomp-profile-restricted/initcontainers/binding.yaml
  - seccomp-profile-restricted/initcontainers/policy.yaml
  - seccomp-profile-restricted/policy.yaml
  - seccomp-profile/binding.yaml
  - seccomp-profile/containers/binding.yaml
  - seccomp-profile/containers/policy.yaml
  - seccomp-profile/ephemeralcontainers/binding.yaml
  - seccomp-profile/ephemeralcontainers/policy.yaml
  - seccomp-profile/initcontainers/binding.yaml
  - seccomp-profile/initcontainers/policy.yaml
  - seccomp-profile/policy.yaml
  - selinux-role/binding.yaml
  - selinux-role/containers/binding.yaml
  - selinux-role/containers/policy.yaml
  - selinux-role/ephemeralcontainers/binding.yaml
  - selinux-role/ephemeralcontainers/policy.yaml
  - selinux-role/initcontainers/binding.yaml
  - selinux-role/initcontainers/policy.yaml
  - selinux-role/policy.yaml
  - selinux-type/binding.yaml
  - selinux-type/containers/binding.yaml
  - selinux-type/containers/policy.yaml
  - selinux-type/ephemeralcontainers/binding.yaml
  - selinux-type/ephemeralcontainers/policy.yaml
  - selinux-type/initcontainers/binding.yaml
  - selinux-type/initcontainers/policy.yaml
  - selinux-type/policy.yaml
  - selinux-user/binding.yaml
  - selinux-user/containers/binding.yaml
  - selinux-user/containers/policy.yaml
  - selinux-user/ephemeralcontainers/binding.yaml
  - selinux-user/ephemeralcontainers/policy.yaml
  - selinux-user/initcontainers/binding.yaml
  - selinux-user/initcontainers/policy.yaml
  - selinux-user/policy.yaml
  - startupprobe-httpget-host/containers/binding.yaml
  - startupprobe-httpget-host/containers/policy.yaml
  - startupprobe-httpget-host/initcontainers/binding.yaml
  - startupprobe-httpget-host/initcontainers/policy.yaml
  - startupprobe-tcpsocket-host/containers/binding.yaml
  - startupprobe-tcpsocket-host/containers/policy.yaml
  - startupprobe-tcpsocket-host/initcontainers/binding.yaml
  - startupprobe-tcpsocket-host/initcontainers/policy.yaml
  - sysctls/binding.yaml
  - sysctls/policy.yaml
  - volume-types/binding.yaml
  - volume-types/policy.yaml
  - windows-hostprocess/binding.yaml
  - windows-hostprocess/containers/binding.yaml
  - windows-hostprocess/containers/policy.yaml
  - windows-hostprocess/ephemeralcontainers/binding.yaml
  - windows-hostprocess/ephemeralcontainers/policy.yaml
  - windows-hostprocess/initcontainers/binding.yaml
  - windows-hostprocess/initcontainers/policy.yaml
  - windows-hostprocess/policy.yaml
