apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: check-readinessprobe-httpget-host-initcontainers
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  validations:
    - expression: >
        !has(object.spec.initContainers) ||
        object.spec.initContainers.all(ic,
          !has(ic.readinessProbe) ||
          !has(ic.readinessProbe.httpGet) ||
          !has(ic.readinessProbe.httpGet.host) ||
          ic.readinessProbe.httpGet.host == ""
        )
      message: >
        spec.initContainers[*].readinessProbe.httpGet.host must be undefined or empty ("").
