apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: check-readinessprobe-httpget-host-containers
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  validations:
    - expression: >
        object.spec.containers.all(c,
          !has(c.readinessProbe) ||
          !has(c.readinessProbe.httpGet) ||
          !has(c.readinessProbe.httpGet.host) ||
          c.readinessProbe.httpGet.host == ""
        )
      message: >
        spec.containers[*].readinessProbe.httpGet.host must be undefined or empty ("").
