apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: check-selinux-role
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  validations:
    - expression: >
        !has(object.spec.securityContext) ||
        !has(object.spec.securityContext.seLinuxOptions) ||
        !has(object.spec.securityContext.seLinuxOptions.role) ||
        object.spec.securityContext.seLinuxOptions.role == ""
      message: >
        spec.securityContext.seLinuxOptions.role must be undefined or an empty string ("").
