apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: check-selinux-user
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  validations:
    - expression: >
        !has(object.spec.securityContext) ||
        !has(object.spec.securityContext.seLinuxOptions) ||
        !has(object.spec.securityContext.seLinuxOptions.user) ||
        object.spec.securityContext.seLinuxOptions.user == ""
      message: >
        spec.securityContext.seLinuxOptions.user must be undefined or an empty string ("").
