apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: check-startupprobe-tcpsocket-host-containers
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  validations:
    - expression: >
        object.spec.containers.all(c,
          !has(c.startupProbe) ||
          !has(c.startupProbe.tcpSocket) ||
          !has(c.startupProbe.tcpSocket.host) ||
          c.startupProbe.tcpSocket.host == ""
        )
      message: >
        spec.containers[*].startupProbe.tcpSocket.host must be undefined or empty ("").
