apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: check-windows-hostprocess
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods"]
  validations:
    - expression: >
        !has(object.spec.securityContext) ||
        !has(object.spec.securityContext.windowsOptions) ||
        !has(object.spec.securityContext.windowsOptions.hostProcess) ||
        object.spec.securityContext.windowsOptions.hostProcess == false
      message: >
        HostProcess is not allowed. spec.securityContext.windowsOptions.hostProcess
        must be undefined or set to false.
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: check-windows-hostprocess-namespace-optout-warn
spec:
  policyName: check-windows-hostprocess
  validationActions:
    - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: validating-admission-policies.kolteq.com/warn
          operator: In
          values: ["baseline", "restricted"]
        - key: validating-admission-policies.kolteq.com/windows-hostprocess
          operator: NotIn
          values: ["false"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: check-windows-hostprocess-namespace-optin-warn
spec:
  policyName: check-windows-hostprocess
  validationActions:
    - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: windows-hostprocess.validating-admission-policies.kolteq.com/warn
          operator: In
          values: ["true"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: check-windows-hostprocess-namespace-optout-audit
spec:
  policyName: check-windows-hostprocess
  validationActions:
    - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: validating-admission-policies.kolteq.com/audit
          operator: In
          values: ["baseline", "restricted"]
        - key: validating-admission-policies.kolteq.com/windows-hostprocess
          operator: NotIn
          values: ["false"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: check-windows-hostprocess-namespace-optin-audit
spec:
  policyName: check-windows-hostprocess
  validationActions:
    - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: windows-hostprocess.validating-admission-policies.kolteq.com/audit
          operator: In
          values: ["true"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: check-windows-hostprocess-namespace-optout-deny
spec:
  policyName: check-windows-hostprocess
  validationActions:
    - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: validating-admission-policies.kolteq.com/enforce
          operator: In
          values: ["baseline", "restricted"]
        - key: validating-admission-policies.kolteq.com/windows-hostprocess
          operator: NotIn
          values: ["false"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: check-windows-hostprocess-namespace-optin-deny
spec:
  policyName: check-windows-hostprocess
  validationActions:
    - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: windows-hostprocess.validating-admission-policies.kolteq.com/enforce
          operator: In
          values: ["true"]
