apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: check-windows-hostprocess-ephemeralcontainers
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["pods/ephemeralcontainers"]
  validations:
    - expression: >
        !has(object.spec.ephemeralContainers) ||
        object.spec.ephemeralContainers.all(c,
          !has(c.securityContext) ||
          !has(c.securityContext.windowsOptions) ||
          !has(c.securityContext.windowsOptions.hostProcess) ||
          c.securityContext.windowsOptions.hostProcess == false
        )
      message: >
        HostProcess is not allowed for ephemeral containers. Each
        spec.ephemeralContainers[*].securityContext.windowsOptions.hostProcess
        must be undefined or set to false.
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: check-windows-hostprocess-ephemeralcontainers-namespace-optout-warn
spec:
  policyName: check-windows-hostprocess-ephemeralcontainers
  validationActions:
    - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: validating-admission-policies.kolteq.com/warn
          operator: In
          values: ["baseline", "restricted"]
        - key: validating-admission-policies.kolteq.com/windows-hostprocess-ephemeralcontainers
          operator: NotIn
          values: ["false"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: check-windows-hostprocess-ephemeralcontainers-namespace-optin-warn
spec:
  policyName: check-windows-hostprocess-ephemeralcontainers
  validationActions:
    - Warn
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: windows-hostprocess-ephemeralcontainers.validating-admission-policies.kolteq.com/warn
          operator: In
          values: ["true"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: check-windows-hostprocess-ephemeralcontainers-namespace-optout-audit
spec:
  policyName: check-windows-hostprocess-ephemeralcontainers
  validationActions:
    - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: validating-admission-policies.kolteq.com/audit
          operator: In
          values: ["baseline", "restricted"]
        - key: validating-admission-policies.kolteq.com/windows-hostprocess-ephemeralcontainers
          operator: NotIn
          values: ["false"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: check-windows-hostprocess-ephemeralcontainers-namespace-optin-audit
spec:
  policyName: check-windows-hostprocess-ephemeralcontainers
  validationActions:
    - Audit
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: windows-hostprocess-ephemeralcontainers.validating-admission-policies.kolteq.com/audit
          operator: In
          values: ["true"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: check-windows-hostprocess-ephemeralcontainers-namespace-optout-deny
spec:
  policyName: check-windows-hostprocess-ephemeralcontainers
  validationActions:
    - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: validating-admission-policies.kolteq.com/enforce
          operator: In
          values: ["baseline", "restricted"]
        - key: validating-admission-policies.kolteq.com/windows-hostprocess-ephemeralcontainers
          operator: NotIn
          values: ["false"]
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: check-windows-hostprocess-ephemeralcontainers-namespace-optin-deny
spec:
  policyName: check-windows-hostprocess-ephemeralcontainers
  validationActions:
    - Deny
  matchResources:
    namespaceSelector:
      matchExpressions:
        - key: windows-hostprocess-ephemeralcontainers.validating-admission-policies.kolteq.com/enforce
          operator: In
          values: ["true"]
