apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: check-capabilities-drop-all-initcontainers
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE"]
        resources: ["pods"]
  validations:
    - expression: >
        (has(object.spec.os) &&
         has(object.spec.os.name) &&
         object.spec.os.name.lowerAscii() == "windows") ||
        !has(object.spec.initContainers) ||
        object.spec.initContainers.all(ic,
          has(ic.securityContext) &&
          has(ic.securityContext.capabilities) &&
          has(ic.securityContext.capabilities.drop) &&
          ic.securityContext.capabilities.drop.exists(d, d == "ALL")
        )
      message: >
        spec.initContainers[*].securityContext.capabilities.drop must exist and include "ALL".
