name: Test Policies

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
    workflow_dispatch:

jobs:
  test-policies:
    name: Test Policies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
          version: v0.31.0

      - name: Run Policy Tests
        run: ./run-policy-tests.sh

